# Generated by Django 4.2.3 on 2024-03-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=20)),
                ('alert_id', models.CharField(max_length=128, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(max_length=50)),
                ('verification_expiration', models.DateTimeField()),
                ('chat_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatternAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertcount', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('alert_medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxmktwatch.alertmedium')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxmktwatch.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=30)),
                ('setup_condition', models.CharField(max_length=50)),
                ('target_price', models.FloatField()),
                ('timeframe', models.CharField(max_length=4)),
                ('repeat_alarm', models.PositiveSmallIntegerField(default=1)),
                ('alertcount', models.IntegerField(default=0)),
                ('status', models.CharField(default=0, max_length=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('expiration_unit', models.CharField(max_length=10)),
                ('expiration_value', models.PositiveSmallIntegerField(default=1)),
                ('expiration', models.DateTimeField()),
                ('note', models.CharField(max_length=100)),
                ('alert_medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxmktwatch.alertmedium')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxmktwatch.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='alertmedium',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxmktwatch.userinfo'),
        ),
    ]
