# Generated by Django 4.2.3 on 2023-08-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxmktwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='alertcount',
            field=models.IntegerField(default=0),
        ),
    ]
