# Generated by Django 4.2.3 on 2023-09-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxmktwatch', '0002_alter_alerts_alertcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='currency_pair',
            field=models.CharField(max_length=30),
        ),
    ]
