# Generated by Django 4.2.3 on 2023-09-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxmktwatch', '0003_alter_alerts_currency_pair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='condition',
            new_name='setup_condition',
        ),
    ]
